services:
  - type: web
    name: teacher-dashboard-backend
    env: python
    region: oregon       # Change region if needed
    plan: free           # Free tier
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn Eduvista_backend_render.wsgi
    envVars:
      - key: SECRET_KEY
        fromSecret: "06boh)f%lm7sp%qe!o9=^f6ga*-4$oyxxqqd&vg&k(3qgnn$gp"
      - key: DEBUG
        value: "False"     # Optional if using Postgres
      - key: SUPABASE_URL
        fromSecret: "https://wztqimzxyfsedozseqxt.supabase.co"
      - key: SUPABASE_KEY
        fromSecret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dHFpbXp4eWZzZWRvenNlcXh0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Njk2NjYzNSwiZXhwIjoyMDcyNTQyNjM1fQ.AQjnD_miVhCQUsdTpYgJXcQLN5bRwFioDt3CU-M_FCI"
      - key: CORS_ALLOWED_ORIGIN
        value: "https://eduvista-frontend-ukqp.vercel.app" # Add your frontend Vercel URL for production
