from django.urls import path
from . import views

urlpatterns = [
    path("students/", views.students_list),
    path("teachers/", views.teachers_list),
    path("subjectsAdmin/", views.subjects),
    path("exams/", views.exams_list),
    path("marks/<str:subject_id>/<int:class_id>/<str:exam_type>", views.marks_list),
    path("grades/<str:teacher_id>/<str:subject_id>/<int:class_id>/<str:exam_type>", views.grades_list),
    path("marks_update/", views.marks_update),
    path("classes/<str:teacher_id>/<str:subject_id>", views.class_list),
    path("subjects/<str:teacher_id>/", views.subject_list),
    path("subject/<str:teacher_id>/<int:class_id>", views.getSubject),
    path("myclass/students/<int:my_class_id>/", views.students_of_my_class, name="students_of_my_class_with_id"),
    path("mark_attendance/", views.mark_attendance),
    path("reports/<int:student_id>", views.final_reports),
    path("gen/<int:student_id>",views.gen_pdf),
    path("login/", views.supabase_login_api, name="api_login"),
    path("signup/", views.supabase_signup_api, name="api_signup"),
    path("home/<str:user_id>", views.home_api, name="api_home"),
    path("logout/", views.logout_api, name="api_logout"),
    path("behaviour/<int:student_id>",views.behavioural_analysis),
    path("student_update",views.update_students),
    path("parent_update",views.update_teacher),
    path("update_exam",views.exam_management),
    path('student/<int:student_id>/payment-history/', views.student_payment_history, name='student_payment_history'),
    path('student/<int:student_id>/upcoming-dues/', views.student_upcoming_dues, name='student_upcoming_dues'),
    path('student/<int:student_id>/transport/', views.student_transport_details, name='student_transport_details'),
]
